spring:
  devtools:
    restart:
      enabled: true
  thymeleaf:
    prefix: file:src/main/resources/templates/
    cache: false
  resources:
    static-locations: file:src/main/resources/static/
    cache: false
  queries:
    user-query: select user_email, password, active from users where user_email=?
    roles-query: select u.user_email, r.role from users u inner join user_roles ur on(id=ur.user_id) inner join roles r on(ur.role_id=r.id) where u.user_email=?
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.99.100:3306/quotes_db
    username: root
    password: abc123
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: debug

