spring:
  queries:
    user-query: select email, password, active from user where email=?
    roles-query: select u.email, r.role from user u inner join user_role ur on(u.user_id=ur.user_id) inner join role r on(ur.role_id=r.role_id) where u.email=?
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://192.168.99.100:3306/quotes_db
    username: root
    password: abc123
    hikari:
      minimum-idle: 1
      maximum-pool-size: 3
  main:
    allow-bean-definition-overriding: true
logging:
  level:
    org.springframework: debug
